### PR TITLE
Use Pygithub object instead of url_request

### PR DESCRIPTION
**Pull request by ttran428**
Changed the functions find_pr_info and find_issues_info to use the github object instead to increase api calls.

### CODE REVIEW

**Comment by stefanv** [comment]
Teddy, is this good to go?  I see conflicts, and also it looks like you committed your key.

**Comment by ttran428** [comment]
I deleted my key(I forgot to commit that change last time I think) and I fixed the conflicts by merging the upstream into my branch.

**Comment by stefanv** [comment]
You now have `doc/docs.zip` committed.

After removing, please ask @SeraYang1 to review and merge if she's happy.

**Comment by ttran428** [comment]
sounds good. I will ask her.

**Review by SeraYang1 — APPROVED** [review]

**Pull request merged**
