### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by ttran428**
Added documentation. Removed _build folder. If you want to have an empty _build folder though, I'm not sure how to do that on git.

### CODE REVIEW

**Comment by ttran428** [comment]
Added one more command to the documentation.

**Comment by stefanv** [comment]
This branch is now in conflict with master.

**Comment by ttran428** [comment]
Resolved the conflicts.

**Comment by stefanv** [comment]
If this is only documentation, why does it modify `git-hub`?

**Comment by ttran428** [comment]
fixed.

**Pull request merged**
